# Generated by Django 3.2.13 on 2022-05-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
