# Generated by Django 3.2.13 on 2022-05-21 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20220521_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['vote_count']},
        ),
        migrations.AddField(
            model_name='post',
            name='vote_count',
            field=models.IntegerField(default='0', verbose_name=models.ManyToManyField(blank=True, related_name='post_votes', to=settings.AUTH_USER_MODEL)),
        ),
    ]
