# Generated by Django 3.2.13 on 2022-05-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20220521_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_count',
        ),
    ]
